### PR TITLE
Link to other houses in the house/download page

### LINKED ISSUE #15259: Reword the house download page
This is part of #15240, until #13598 is merged.

# Problem

In the house/download page, we have a "Want politicians who aren’t from [this country]?" section, but don't explain what to do if you want politicians from a different house in the same country.

Example: [http://localhost:4567/united-states-of-america/senate/download.html](http://localhost:4567/united-states-of-america/senate/download.html)

page

# Proposed Solution

Reword the copy at bottom of house/download page and link to the other houses.

# Acceptance Criteria

Visitors know how to access data for other houses of a country from a country's legislature page.

### PR DESCRIPTION
**Pull request by octopusinvitro**
## What does this do?

Links to other houses in the same country in the house/download page, because at the moment that section links to other countries only.

## Why was this needed?

After merging the house/download page, it was clear that either a reword of the bottom of that page was needed (#15259) or either to go for the tab component integration directly (#15240). We changed our mind and went for the first one instead.

## Relevant Issue(s)

* Closes #15259 (Reword the house download page). 
* Last point in the first section of the workflow described in todo list #15256.

## Implementation notes

Adds:
* New method in the House/download page to check if there are other houses
* New method in the House/download page to get the other houses
* Tests to check that the link to other houses are displayed correctly and with the right information
* Updates the template.

At the moment there are no countries with more than two houses. If there were more than two, the links would just been added after each other.

## Screenshots

**Country with more than one legislature:**

Australia. Go to [http://localhost:5000/australia/representatives/download.html](http://localhost:5000/australia/representatives/download.html)

australia

**Country with only one legislature:**

Panama. Go to [http://localhost:5000/panama/assembly/download.html](http://localhost:5000/panama/assembly/download.html)

panama

**Country with three legislatures:**

A country like this doesn’t exist yet. But if it did, the “Other legislatures” section would look like this:

screen shot 2016-10-03 at 12 45 12

## Notes to Reviewer

None

## Notes to Merger

NONE :tada: :balloon: 

## Related legacy links

This PR replaces #15426

### CODE REVIEW

**Comment by zarino** [comment]
A while back, https://github.com/everypolitician/viewer-sinatra/pull/13598 proposed a level of navigation *inside* a country, in the style of tabs:

screen shot 2016-07-25 at 14 15 11

And even way back then, we were talking about using the same tabs on the Download page.

(In the end, the PR floundered, because after implementing it, we realised the tabs only helped you navigate laterally between legislatures, and we had no idea how they should best navigate *temporally*, through past terms.)

So, @tmtmtmtm, the question is: Is this PR an opportunity to use that tab UI, or do you just want an MVP tidy up of the spacing and styling of @octopusinvitro’s existing buttons?

**Comment by tmtmtmtm** [comment]
@zarino, right now I'm not convinced that tabs are going to be a good plan. My thinking:

1) Tabs only work if you're going to be switching between different versions of the same thing
2) Here, that would certainly make sense — you'd get an equivalent download page for the other house
3) However, for most other pages 'under' a legislature there won't _be_ an equivalent page
4) If people see these tabs on some pages, they'll expect them on others, even where there isn't an equivalent page

I'm definitely open to persuasion that my thinking is completely off, or that there's a way to resolve this, as I think having some way of getting between lower and upper chambers in a general way is going to be useful. But I suspect an MVP approach might be better in the short-term.

**Comment by octopusinvitro** [comment]
@tmtmtmtm I've rebased the branch with master.

**Comment by zarino** [comment]
@tmtmtmtm I've given the page a bit more structure, and bumped the headings up to `<h2>` for the three main page sections (this legislature, other legislatures, other countries) and `<h3>` for the rest. The “Other legislatures” and “Other countries” sections are all centre aligned – it's the most expedient way of handling the dramatically different text lengths in the various parts. It looks a bit spindly on very wide screens, but should be fine for something at the bottom of a fairly low traffic page.

I’ve updated the screenshots at the top of the thread, to reflect the new styling.

@octopusinvitro The tests appear to be failing, but I can’t tell whether that’s my fault.

**Comment by octopusinvitro** [comment]
@zarino Thank you! that is so :sparkles: shiny :sparkles: 

The tests are failing because the erb file was modified, I will fix that :slightly_smiling_face:

**Comment by octopusinvitro** [comment]
@tmtmtmtm feedback addressed. I modified the two tests that were failing due to the changes in the erb file made by Zarino and added them as a fixup to his commit since the modification of the erb file and the update of the tests should be together.

@zarino tests fixed :slightly_smiling_face:

**Comment by tmtmtmtm** [comment]
Woot! Thanks @zarino and @octopusinvitro

**Pull request merged**
