### PR TITLE
Update installation instructions for this fork

### PR DESCRIPTION
**Pull request by andylolz**

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Thanks @andylolz. (I'm not sure why Travis is failing on that test, but I'm assuming it's a transitory thing as the other one passed)

**Comment by andylolz** [comment]
Yeah, weird. All tests seem to pass, but non-zero exit code.

**Comment by dracos** [comment]
Pull requests from external repositories do not have access to secure information (as they could then find that out by adding a `printenv` and submitting a PR). Looks like `scripts/release.sh` assumes it can see those keys and dies at the SSH key bit.

**Comment by andylolz** [comment]
Ahh gotcha, thanks @dracos. PR sent that possibly helps?

**Comment by tmtmtmtm** [comment]
Thanks @andylolz. I'm going to leave this one for @chrismytton to look at next week, in case there are any implications here that I'm not aware of.

**Comment by andylolz** [comment]
Yeah, good plan. I don’t really know what `scripts/release.sh` is doing, so it’s just a guess on my part really.

Sorry to keep distracting you from the business of scraping!

**Pull request merged**
