### PR TITLE
Reconciliation with html interface

### PR DESCRIPTION
**Pull request by everypoliticianbot**
Commits:

- Generate an html reconciliation file instead of CSV
- Add list of people into a dl
- Allow removing a match from the table
- Generate a CSV with the sorted table
- Add incoming id to the generated html file
- Add some bootstrap styles
- Make Reconciler parameter names clearer
- If we have two ids then reconcile directly on the id
- WIP Drag and drop-ish
- Add uuids to incoming membership rows
- Use UUID in generated html file
- Reorder reconciliation csv so we always match on first column
- Merge branch 'master' into reconciliation-csv
- Move reconciliation html into an ERB template
- Use Yajl to safely encode JSON in html
- Fix CSV output in reconciliation html
- Tidy up js and html in reconciliation interface
- Include all rows in reconciliation html
- Remove unused code to write reconciliation CSV
- Revert draggable if not dropped correctly in reconciliation
- Merge branch 'master' into reconciliation-csv
- Move reconciliation javascript into separate file
- Allow the user to choose from existing rows when merging
- Allow searching for existing person with select2 dropdown
- Fix typo in reconciliation html copy
- Use unique merged rows in reconciliation html
- Switch to Google's hosted js libs for reconciliation
- Use Papa Parse to generate the reconciliation CSV
- git-ignore the reconciliation HTML files

https://github.com/everypolitician/everypolitician-data/pull/1125

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@chrismytton : why does this PR exist? I thought the parallel PRs were only opened if the EP-data one included a change to `countries.json`, which 1125 didn't…

**Comment by chrismytton** [comment]
> I thought the parallel PRs were only opened if the EP-data one included a change to countries.json

Oops, this is a bug. I've ticketed in https://github.com/everypolitician/app-manager/issues/45, it's a tiny fix so will do that now.

**Comment by chrismytton** [comment]
I've deployed a fix in https://github.com/everypolitician/app-manager/pull/46 live now so this shouldn't happen again.

**Comment by tmtmtmtm** [comment]
Yay, thanks @chrismytton

**Pull request closed without merging**
