### PR TITLE
Use space-less version of EveryPolitician logo everywhere

### PR DESCRIPTION
**Pull request by zarino**
screen shot 2015-10-06 at 17 28 28

Fixes everypolitician/everypolitician#158

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
thanks @zarino :rocket:

**Comment by zarino** [comment]
@tmtmtmtm I have a new version of our logo for you to add to the Morph.io profile – shall I email it to you?

**Comment by tmtmtmtm** [comment]
I don't think there's any way to update that directly in Morph — it just picks it up from Github, so if you change it there, it should wend its way across.

**Comment by zarino** [comment]
Oh that's a shame. But not the end of the world.

**Comment by tmtmtmtm** [comment]
Looks like it's already picked it up: https://morph.io/everypolitician

**Pull request merged**
