### PR TITLE
First steps towards documentation

### PR DESCRIPTION
**Pull request by tmtmtmtm**
Add YARD, and add some initial documentation of a single class (Page::Home). 

There are undoubtedly lots of ways to improve on this, but this is initially just seeing how the basic approach works before rolling it out everywhere.

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Running `yard server --reload` is useful for generating the documentation whilst creating/editing it, but it's not totally clear to me how we should actually publish this normally. Are we meant to run `yard doc` and then check that in?

**Comment by tmtmtmtm** [comment]
@chrismytton thoughts? suggestions? ideas? Should we be using something else instead?

**Comment by chrismytton** [comment]
> Running yard server --reload is useful for generating the documentation whilst creating/editing it, but it's not totally clear to me how we should actually publish this normally. Are we meant to run yard doc and then check that in?

You can see the generated documentation on [rubydoc.info](http://www.rubydoc.info/github/everypolitician/viewer-sinatra/yard/Page/Home) (that link is for this `yard` branch)

> @chrismytton thoughts? suggestions? ideas? Should we be using something else instead?

Big 👍  from me! We might also want to add [`yard-sinatra`](https://github.com/rkh/yard-sinatra) (semi-official, since it's written by Sinatra's primary maintainer) which adds Sinatra routes to the documentation. The main alternatives are TomDoc and RDoc, but neither of those have as much momentum in the Ruby community AFAIK.

**Comment by tmtmtmtm** [comment]
Good call on yard-sinatra: ticket for that opened at https://github.com/everypolitician/viewer-sinatra/issues/15306

**Pull request merged**
