### PR TITLE
Add nav to docs

### PR DESCRIPTION
**Pull request by davewhiteland**
this has added a couple of column-wrangling divs to each of the docs pages, which has changed the indenting on the body of the texts, but I don't think there are material changes in the words :-)

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
screen shot 2015-08-07 at 16 31 07

**Comment by tmtmtmtm** [comment]
@davewhiteland was dropping the "the" in "Getting most recent data" deliberate?

**Comment by davewhiteland** [comment]
yup, I suspect the line might be too long with it, but that's a bit hand-wavy how-long-is-a-piece-of-[in-this-font]-string

**Comment by tmtmtmtm** [comment]
Looks great then! :shipit:

**Pull request merged**
