### PR TITLE
Promote Gender Balance on country pages

### LINKED ISSUE #464: Link to GenderBalance
We should provide a link to GenderBalance, especially for countries where we don't have gender data already.

### PR DESCRIPTION
**Pull request by zarino**
Fixes #464.

Also includes a slightly tidied up Country page, with a clear header section in grey, and better spacing between assemblies in multiple-assembly countries.

# Desktop

screen shot 2015-08-04 at 17 15 48

# Tablet

screen shot 2015-08-04 at 17 16 27

# Phone

screen shot 2015-08-04 at 17 16 52

### CODE REVIEW

**Comment by zarino** [comment]
@MyfanwyNixon – Any changes to the wording?

@tmtmtmtm @jacksonj04 – The links just go straight to http://gender-balance.org – is there any magic analytics tracking you want to add so you can see how many people come via everypolitician.org?

**Comment by tmtmtmtm** [comment]
@zarino @jacksonj04 do we automatically get basic referred info anyway? Or is it worth adding something?

On wording, if @MyfanwyNixon wants to change anything when she gets back, happy to make those changes, but this seems good enough for now :)  :shipit:

**Comment by tmtmtmtm** [comment]
@zarino, I'm wondering if it's possible to free up a little more space for this to have a chance of appearing on a laptop-size screen? Here's how it looks for me:

screen shot 2015-08-06 at 12 46 53

We don't want to make the page too cluttered, but there's a _lot_ of whitespace pushing this way down…

**Comment by jacksonj04** [comment]
@tmtmtmtm is right in that we get referral info anyway - the only additional thing that might be worth adding is the [campaign tracking](https://support.google.com/analytics/answer/1033863), but it's got very limited benefits that I can see.

**Comment by zarino** [comment]
@tmtmtmtm – Here's a PR for reducing the vertical padding https://github.com/everypolitician/viewer-sinatra/pull/485

**Comment by MyfanwyNixon** [comment]
:+1: Wording looks good to me.

**Pull request merged**
