### PR TITLE
add standardised mysociety footer

### PR DESCRIPTION
**Pull request by wrightmartin**
Adds the standardised footer for use on all mySociety sites

(please check the links and blurb I've put in are as desired and correct)

screen shot 2016-06-03 at 14 34 07

Closes https://github.com/everypolitician/everypolitician/issues/388

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@wrightmartin what's with the horse logos?

**Comment by tmtmtmtm** [comment]
@wrightmartin I'm confused as to what's happening here. This only seems to be image files — with no changes to CSS or templates, or the like.

Is this still work-in-progress, or did you forget to check some things in?

Also, does this provide the new grid Zarino [suggested yesterday would be likely](https://github.com/everypolitician/viewer-sinatra/pull/10620#issuecomment-223282794)?

**Comment by wrightmartin** [comment]
> Is this still work-in-progress, or did you forget to check some things in? 

My check in went a bit awry, all fixed now

> Also, does this provide the new grid Zarino suggested yesterday would be likely?

It doesn't, no as I've adapted it to use what's already there in EP's layout code. Do you want me to open a ticket to refactor/replace the grid system for EP so it's easier for everyone to use?

**Comment by tmtmtmtm** [comment]
> Do you want me to open a ticket to refactor/replace the grid system for EP so it's easier for everyone to use?

@davewhiteland any views on this?

**Comment by tmtmtmtm** [comment]
> please check the links and blurb I've put in are as desired and correct

I suspect we'll want to tweak those. The links, in particular, seem quite disjointed. Over to @davewhiteland for comments / suggestions…

**Comment by davewhiteland** [comment]
As for the grids: I guess if it's the same across all our sites that won't do any harm, but it doesn't seem like a pressing need since it's not currently broken; if all the useful styles are presented in the `styling` pages (which is superhelpful) then that feels more important than consistency across repos to me.

I've updated the 6 links and have committed+pushed to this branch.

**Comment by davewhiteland** [comment]
@tmtmtmtm  for approval and merge please

**Comment by tmtmtmtm** [comment]
Now:

screen shot 2016-06-24 at 09 15 27

**Comment by tmtmtmtm** [comment]
@davewhiteland @wrightmartin is this also to be used on http://docs.everypolitician.org/? Is that ready to go live at the same time?

**Comment by davewhiteland** [comment]
@tmtmtmtm good spot, added it now as everypolitician/everypolitician-docs#21

**Pull request merged**
