### PR TITLE
Hide Party Groupings section if there is only one party and it is “Unknown”

### LINKED ISSUE #5265: Don't show Party Groupings when all are unknown
screen shot 2016-03-14 at 22 46 02

### PR DESCRIPTION
**Pull request by zarino**
Fixes #5265.

Eg: /transnistria/supreme-council/term-table/6.html

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Now:

screen shot 2016-03-16 at 14 56 20

Was:
screen shot 2016-03-16 at 14 56 40

**Comment by tmtmtmtm** [comment]
@chrismytton do you want to hoist that commented logic up into `app.rb`?

**Comment by chrismytton** [comment]
> do you want to hoist that commented logic up into app.rb?

Yep, done. I think this is ready to be merged now.

**Comment by chrismytton** [comment]
I need to build on top of the logic I moved into `app.rb`, so I'm going to merge this into `master`.

**Pull request merged**
