### PR TITLE
Suggest examples of what to search for in js-filter-input

### LINKED ISSUE #5264: Signpost how people can filter
(from @paullenz at https://github.com/everypolitician/everypolitician/issues/339#issuecomment-196796228)

It is unclear here - to a lay person such as me - what exactly I can filter on (I was expecting a drop down) some signpost text e.g. enter a name or place or party

screenshot 2016-03-11 17 14 26

### PR DESCRIPTION
**Pull request by zarino**
Fixes #5264.

screen shot 2016-03-16 at 13 17 21

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
Looks good, though I'd avoid the word 'party' here, as in lots of countries the groups very much *aren't* parties.

**Comment by zarino** [comment]
@tmtmtmtm Is there wording you'd prefer then?

**Comment by tmtmtmtm** [comment]
The generic term would just be "group" but that's not going to be meaningful to lots of people so we often fall back on "party/faction".

**Comment by zarino** [comment]
For now, I’ve just removed party entirely.

screen shot 2016-03-17 at 09 39 19

**Pull request merged**
