### PR TITLE
Add the map to the Data page

### LINKED ISSUE #170: Make the Country List page look nicer
At the moment http://data.everypolitician.org/ is a separate homepage with a list of countries. Ideally we'll consolidate the sites into one (requires #120), but we'll always need _something_ to show which countries we have, and a non-zoomable map on its own isn't enough. 

Unless or until we resolve the wider issue, it's probably worth doing something quite basic to make the http://data.everypolitician.org/ page itself slightly nicer.

### PR DESCRIPTION
**Pull request by tmtmtmtm**
Once we put the new homepage (#303) live, we'll no longer have the map that's on the existing jekyll homepage. So let's pre-emptively add it to the big list-of-countries page. 

screen shot 2015-07-07 at 15 22 55

Closes #170

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@zarino Any objections to me simply putting this version live already, and iterating from there? It uses the `:new_layout`, and I'm not sure whether you're happy enough with that yet to actually put something live using it.

My working assumption is that it's better for me to push as much of this stuff live as possible, and then have you clean up the stuff that isn't quite right, than have you do all of this fiddly work. But that actually slows you down, and you'd be happier just implementing everything yourself, that's fine too :)

[NB: You can click the 'deployed' link above to see the staged version of this on heroku]

**Comment by zarino** [comment]
@tmtmtmtm – Go for it!

**Comment by zarino** [comment]
@tmtmtmtm – if anything, I'd add just a bit of margin below the map. `#vmap { margin-bottom: 2em }` should do it.

**Comment by tmtmtmtm** [comment]
Great. At the minute the map styling is just inlined on the div, so I've added it there. That's the sort of thing you can feel free to tidy up later if you have time :)

**Pull request merged**
